"""first models

Revision ID: 1eb7f130eb6
Revises: 
Create Date: 2015-10-18 01:18:20.062051

"""

# revision identifiers, used by Alembic.
revision = '1eb7f130eb6'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('blog_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.blog_id'], ),
    sa.PrimaryKeyConstraint('entry_id'),
    sa.UniqueConstraint('blog_id', 'name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_table('blogs')
    ### end Alembic commands ###
